# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jairo Honorio
email: jairo@jahdsoft.com
description: >
  Software Engineer
hero: "/assets/images/header-image.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jairo.jahdsoft.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Jairo Honorio'
designed: Website designed by Karen Honorio
karencontact: "https://www.linkedin.com/in/karen-caroline-honorio-banci-198827112/"
bio: >
  Consultant specialist in Android, LAMP Fullstack, and videogames.
  I give my best effort at every activity.
author_image: "/assets/images/author.jpg"
twitter_username: JairoAHD
github_username:  jahd2602

# Google Analytics
analytics_id: "UA-37438543-3"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

about:
  title: About me
  description: Jairo Honorio founded multiple companies including game studios such as JahdSoft and Javary, and led various teams up to 6 engineers. Today, Jairo is a Senior Software Engineer that works with AI virtual assistants in Smart Displays and Wearables at Google.


timeline: Timeline


companies:
  - name: Google
    logo: ./assets/images/logo-google.png
    start: Feb, 2022
    finish: Present
    field: Senior Technical Solutions Consultant, Partner Engineer
    description:
    local: Mountain View, CA ðŸ‡ºðŸ‡¸
    type: Job

  - name: Oppia Fundation
    logo: ./assets/images/oppia.jpeg
    start: Feb, 2022
    finish: Present
    field: Software Engineer
    description: Typescript, Angular, Jasmine, Mocka, Karma
    local: Mountain View, CA ðŸ‡ºðŸ‡¸
    type: Volunteer

  - name: Google
    logo: ./assets/images/logo-google.png
    start: Oct, 2021
    finish: Feb, 2022
    field: Senior Technical Solutions Consultant, Partner Engineer (Assistant Smart Displays)
    description:
    local: SÃ£o Paulo, SP ðŸ‡§ðŸ‡·
    type: Job

  - name: Google
    logo: ./assets/images/logo-google.png
    start: Feb, 2020
    finish: Oct, 2021
    field: Technical Solutions Consultant, Partner Technology Manager (Assistant Smart Displays)
    description:
    local: SÃ£o Paulo, SP ðŸ‡§ðŸ‡·
    type: Job

  - name: Google Summer of Code
    logo: ./assets/images/google-summer-of-code-icon.svg.png
    start: Aug, 2019
    finish: No expiration date
    field: Mentor for Godot Engine & Mentor Summit Attendee in MÃ¼nich
    description:
    local: MÃ¼nich, Germany ðŸ‡©ðŸ‡ª
    type: volunteer

  - name: Javary Games
    logo: ./assets/images/logo-javary-games.webp
    start: Mar, 2018
    finish: Jan, 2020
    field: CTO
    description: "â†’ Recruit and lead a team of 6 software engineers, 1 music engineer and 1 software tester, plus working with a team of designers and several contractors, to create casual and puzzle games for Android and iOS.
    <br> â†’  Objective-oriented workflow with high focus on app metrics: DAU, ARPU, D1-D7-D30 Retention, Conversion Rate, and more.
    <br> â†’  Create and maintain 10+ native plugins in Java and Objective-C, including Facebook SDK, Firebase, Azure's Playfab, and more.
    <br> â†’  Game engine development using Python, C++ and OpenGL, ensuring high crash-free users (99.98%) and high performance in low-end devices (60 fps).
    <br> â†’  Webserver on top of Amazon Web Services' Lambda server-less platform, attached to a cloud MongoDB instance through NodeJS + Typescript.
    <br> â†’  Use BigQuery language with Google's DataStudio Business Intelligence platform to produce highly relevant reports that directly impact and improve our products."
    local: SÃ£o Paulo, SP ðŸ‡§ðŸ‡·
    type: job

  - name: Godot Engine
    logo: ./assets/images/logo-godot.png
    start: Jun, 2018
    finish: Feb, 2021
    field: Software Engineer
    description: C++
    local: USA ðŸ‡ºðŸ‡¸
    type: volunteer

  - name: Lead Consulting
    logo: ./assets/images/default-job.png
    start: Dec, 2017
    finish: Jan, 2018
    field: Mobile Application Developer - Contract
    description: Developed an application for warehouse workers, that recognizes a variety of barcodes/QR codes, helps to     keep track of inventory and generates a format acceptable for a variety of ERPs.
      Kotlin, Material Design, SQLite, ORMLite.
    local: Lima, Peru ðŸ‡µðŸ‡ª
    type: job

  - name: Ocean Partners UK Limited
    logo: ./assets/images/default-job.png
    start: Jun, 2017
    finish: Sep, 2017
    field: Full-Stack JavaScript Trainer and Consultant
    description: Training in the JavaScript language, the JQuery library and the AngularJS framework, including the use of  other popular JavaScript libraries. On the server side, the usage of NodeJS, NPM and the HAPI server framework, including   the connection with SQL Server and Sharepoint.
      Consulting services to improve legacy subsystems, gaining an important speed boost and improved the overall code organization. We could reduce the loading time of a particular big form from 20+ seconds to <500 ms.
    local: Lima, Peru ðŸ‡µðŸ‡ª
    type: job

  - name: CINFO UNMSM
    logo: ./assets/images/logo-cinfo.png
    start: Jan, 2017
    finish: Mar, 2017
    field: Professor
    description: Introduced OOP and event driven programming concepts through a project-based methodology.
    local: Lima, Peru ðŸ‡µðŸ‡ª
    type: job

  - name: Instrategy
    logo: ./assets/images/default-job.png
    start: Aug, 2016
    finish: Sep, 2016
    field: ETL Consultor (Business Intelligence)
    description: External consultor. Develop a business intelligence ETL strategy for a balance scorecard product deployment, and implement base ETL jobs in Talend Studio.
    local: Lima, Peru ðŸ‡µðŸ‡ª
    type: job

  - name: Universidad Privada Antenor Orrego
    logo: ./assets/images/upao-antenor-orrego-logo2.jpeg
    start: Oct, 2016
    finish: No expiration date
    field: Generador de cÃ³digo de servicios web basado en REST del lado del servidor a partir de archivos de configuraciÃ³n RAML
    description: Flexible code generator tool to produce working web service code from a configuration file, supporting PHP (Silex, Doctrine) and Javascript (NodeJS, ExpressJS, Mongoose). Demo video https://www.youtube.com/watch?v=AufIRxuaS9w
    local: Trujillo, Peru ðŸ‡µðŸ‡ª
    type: education

  - name: Escalabs
    logo: ./assets/images/default-job.png
    start: Oct, 2015
    finish: May, 2016
    field: Project Manager & Tech Lead
    description: I helped develop the business intelligence backend for the marketing area with a small team.
    local: Trujillo, Peru ðŸ‡µðŸ‡ª
    type: job

  - name: Jorvex
    logo: ./assets/images/default-job.png
    start: Jun, 2015
    finish: Aug, 2015
    field: Full stack Software Developer
    description: My job was to finish the development of a hybrid mobile app for a hardware store company. Some features included geolocation tracking of salespeople and clients, product catalog and inventory. Stack, PostgreSQL, Java Servlets, JQuery Mobile, Google Maps API.
    local: Trujillo, Peru ðŸ‡µðŸ‡ª
    type: job

  - name: Treto Enterprises
    logo: ./assets/images/default-job.png
    start: Nov, 2014
    finish: Nov, 2018
    field: Main Software Engineer at Treto Enterprises
    description: â†’ Optimized most used site queries up to 46X leading to a 42.3% increase in page hits.
      â†’ Maintenance and server administration of BuenaMusica.com, a website with 2M+ monthly visitors.
      â†’ Design and development of AcontencerMundial.com.
      â†’ Developed the Android app and other third party solutions, with published MVPs taking less than a week.
      â†’ AngularJS, PHP, MySql, CentOs, Ubuntu, Android.
    local: San Diego, CA ðŸ‡ºðŸ‡¸
    type: job

  - name: MelodiaCristiana.com
    logo: ./assets/images/default-job.png
    start: May, 2014
    finish: Jun, 2014
    field: Mobile Web Software Developer
    description: App development, published in Play Store. Development of the site administration panel. Mobile Angular UI, AngularJS, Phonegap, Android.
    local: Lima, Peru ðŸ‡µðŸ‡ª
    type: job

  - name: Vanderbilt University
    logo: ./assets/images/default-job.png
    start: Sep, 2014
    finish: No expiration date
    field: Programming Cloud Services for Android Handheld Systems
    description:
    local: Trujillo, Peru ðŸ‡µðŸ‡ª
    type: education

  - name: CURSOR S.A.
    logo: ./assets/images/default-job.png
    start: Dec, 2013
    finish: No expiration date
    field: Finalist in Apps Tournament - Sponsored by Google - Santiago de Chile
    description:
    local: Santiago, Chile ðŸ‡¨ðŸ‡±
    type: education

  - name: Universidad Privada Antenor Orrego
    logo: ./assets/images/upao-antenor-orrego-logo2.jpeg
    start: Nov, 2013
    finish: No expiration date
    field: 1st Place - Programming Contest - Intermediate Level - CIISSIT
    description:
    local: Trujillo, Peru ðŸ‡µðŸ‡ª
    type: education

  - name: Universidad Nacional de Trujillo
    logo: ./assets/images/default-job.png
    start: Feb, 2013
    finish: No expiration date
    field: 1st Place - Programming Contest - A Category - SECICOMP
    description:
    local: Trujillo, Peru ðŸ‡µðŸ‡ª
    type: education

  - name: JAHD Soft
    logo: ./assets/images/jahd-logo.png
    start: Aug, 2012
    finish: Feb, 2018
    field: Founder, Software Developer and Project Manager at JAHD Soft
    description: Software development. We make Android, iOS and Web Apps. We have 5+ years working with clients from all around the world.
    local: Lima, Peru ðŸ‡µðŸ‡ª
    type: job

  - name: Universidad Privada Antenor Orrego
    logo: ./assets/images/upao-antenor-orrego-logo2.jpeg
    start: Nov, 2012
    finish: No expiration date
    field: 1st Place - Techonologic Fair - CIISS
    description:
    local: Trujillo, Peru ðŸ‡µðŸ‡ª
    type: education


contact:
  title: Let's Talk!
  description: I build product used by millions. My mission is to be as helpful as possible and bringing joy to people. I can't wait to hear about you!
  linkedin: Linkedin
  email: jairo@jahdsoft.com
